### ISSUE TITLE
Form Bugs

### ISSUE THREAD

**Issue by AbhijnanVegi** [GaurangTandon/election-portal#8]
- [x] The cast vote button breaks sometimes. Picture added below
![image](https://user-images.githubusercontent.com/68379071/131784010-85280f68-4d67-4036-9b94-303c80a671f5.png)
- [x] The view now return a variable `message` with a string stating success or describing errors if any.
- [x] Form error validation fails

**Comment by GaurangTandon** [comment]
Last task done in https://github.com/GaurangTandon/election-portal/commit/ec8ebd0588ea2e901bae0e9ea2ebb09bd7007f2a
